# This is a basic workflow to help you get started with Actions

name: Build fuchsia

on:
  workflow_dispatch:


jobs:



  build:

    runs-on: ubuntu-latest

    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      
      - name: install 
        run: sudo apt install curl file git unzip
        
      - name: download and build
        run: |
          curl -s "https://fuchsia.googlesource.com/fuchsia/+/HEAD/scripts/bootstrap?format=TEXT" | base64 --decode | bash
          ls -lh
          mkdir ~/bin
          PATH=~/bin:$PATH
          rm -rf .git
          cp $(pwd)/.jiri_root/bin/jiri ~/bin
          ln -s $(pwd)/scripts/fx ~/bin
          fx set core.vim3

