# This is a basic workflow to help you get started with Actions

name: Build fuchsia

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      
      - name: install 
        run: sudo apt install curl file git unzip
        
      - name: download and build
        run: |
          curl -s "https://fuchsia.googlesource.com/fuchsia/+/HEAD/scripts/bootstrap?format=TEXT" | base64 --decode | bash
          ls -lh
          cd fuchsia
          ls -lh
          export PATH=$(pwd)/.jiri_root/bin:$PATH
          ./scripts/fx set core.vim3
          ./scripts/fx build
          ./scripts/fx build build-archive.zip

      - name: upload
        uses: actions/upload-artifact@v4
        with:
         name: build-archive
         path: out/default

